name: niallphotos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5632737961132079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.01980547560378909
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
